// <auto-generated />
using System;
using ControlVentas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlVentas.Migrations
{
    [DbContext(typeof(ControlVentaContext))]
    [Migration("20250924162245_inicioProyecto")]
    partial class inicioProyecto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("ControlVentas.Models.Gasto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("eliminado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Gastos");
                });

            modelBuilder.Entity("ControlVentas.Models.Producto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rubro")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("activo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("eliminado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("nombre");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("ControlVentas.Models.Venta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("eliminado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("ControlVentas.Models.VentaDetalle", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("eliminado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("formaPagoEnum")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("precioUnitario")
                        .HasColumnType("TEXT");

                    b.Property<int>("productoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ventaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("productoId");

                    b.HasIndex("ventaId");

                    b.ToTable("VentaDetalles");
                });

            modelBuilder.Entity("ControlVentas.Models.VentaDetalle", b =>
                {
                    b.HasOne("ControlVentas.Models.Producto", "producto")
                        .WithMany()
                        .HasForeignKey("productoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlVentas.Models.Venta", "venta")
                        .WithMany("detalles")
                        .HasForeignKey("ventaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("producto");

                    b.Navigation("venta");
                });

            modelBuilder.Entity("ControlVentas.Models.Venta", b =>
                {
                    b.Navigation("detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
